all:
	rm bin/*
	cp ~/Bin/Blast/blastdbcmd ~/Bin/Blast/blastn ~/Bin/Blast/makeblastdb ./bin/
	cp ~/Bin/macle ~/Bin/phylonium ./bin/
	cp /home/haubold/Programming/C/fur/build/* ./bin/
	docker build -t fox .
