#!/usr/bin/awk -f
#/^>/ {
   n++
 }
#!/^>/ {
   seq[n - 1] = seq[n - 1] $0
 }
END {
  #for (i = 0; i < n; i++) {
     sub(/^NN+/, "", seq[i])
     sub(/NN+$/, "", seq[i])
     gsub(/NN+/, "!", seq[i])
   }
  #for (i = 0; i < n; i++) {
     c = split(seq[i], arr, "\n")
     for (j = 1; i <= c; j++)
       if (length(arr[j]) >= 50)
             printf ">S%d\n%s\n", ++n, arr[j]
   }
}
